server:
  port: 9090

spring:
  data:
    neo4j:
      uri: bolt://localhost:7687 #注意是bolt的端口
      username: neo4j
      password: 12345678
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/knowledge_graph?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 11080420sjx


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键策略：ASSIGN_ID 雪花算法
      id-type: ASSIGN_ID

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

files:
  upload:
    path: /src/main/resources/static/files/
  csv:
    path: /src/main/resources/static/csv/
  neo4j:
    path: /Applications/neo4j-community-5.25.1/import/
  template:
    path: /src/main/resources/static/templateFile/
  unzip:
    path: /src/main/resources/static/unzipFile/
